[package]
name = "blackjack"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
num-format = "0.4.4"
rand = "0.9.0"
rmp-serde = "1.3.0"
serde = { version = "1.0.219", features = ["derive"] }
strum = { version = "0.27.1", features = ["derive"] }
toml = "0.8.20"
